BRAND_ALIAS_MAP = {
    "vw": "Volkswagen",
    "volkswagen": "Volkswagen",
    "大众": "Volkswagen",
    "大眾": "Volkswagen",
    "上汽大众": "Volkswagen",
    "一汽大众": "Volkswagen",
    "一汽-大众": "Volkswagen",
    "toyota": "Toyota",
    "丰田": "Toyota",
    "豐田": "Toyota",
    "一汽丰田": "Toyota",
    "广汽丰田": "Toyota",
    "tesla": "Tesla",
    "特斯拉": "Tesla",
    "byd": "BYD",
    "比亚迪": "BYD",
    "比亞迪": "BYD",
    "honda": "Honda",
    "本田": "Honda",
    "东风本田": "Honda",
    "广汽本田": "Honda",
    "bmw": "BMW",
    "宝马": "BMW",
    "寶馬": "BMW",
    "华晨宝马": "BMW",
    "mercedes": "Mercedes-Benz",
    "mercedes-benz": "Mercedes-Benz",
    "奔驰": "Mercedes-Benz",
    "賓士": "Mercedes-Benz",
    "北京奔驰": "Mercedes-Benz",
    "audi": "Audi",
    "奥迪": "Audi",
    "奧迪": "Audi",
    "一汽奥迪": "Audi",
    "porsche": "Porsche",
    "保时捷": "Porsche",
    "保時捷": "Porsche",
    "ford": "Ford",
    "福特": "Ford",
    "chevrolet": "Chevrolet",
    "雪佛兰": "Chevrolet",
    "上汽通用雪佛兰": "Chevrolet",
    "nissan": "Nissan",
    "日产": "Nissan",
    "日產": "Nissan",
    "东风日产": "Nissan",
    "hyundai": "Hyundai",
    "现代": "Hyundai",
    "現代": "Hyundai",
    "kia": "Kia",
    "起亚": "Kia",
    "起亞": "Kia",
    "lexus": "Lexus",
    "雷克萨斯": "Lexus",
    "volvo": "Volvo",
    "沃尔沃": "Volvo",
    "mazda": "Mazda",
    "马自达": "Mazda",
    "馬自達": "Mazda",
    "subaru": "Subaru",
    "斯巴鲁": "Subaru",
    "geely": "Geely",
    "吉利": "Geely",
    "nio": "NIO",
    "蔚来": "NIO",
    "蔚來": "NIO",
    "xpeng": "XPeng",
    "小鹏": "XPeng",
    "小鵬": "XPeng",
    "li auto": "Li Auto",
    "理想": "Li Auto",
    "mg": "MG",
    "名爵": "MG",
    "roewe": "Roewe",
    "荣威": "Roewe",
    "baojun": "Baojun",
    "宝骏": "Baojun",
    "buick": "Buick",
    "别克": "Buick",
    "上汽通用别克": "Buick",
    "great wall": "Great Wall",
    "长城": "Great Wall",
    "长城汽车": "Great Wall",
    "haval": "Haval",
    "哈弗": "Haval",
    "lynk & co": "Lynk & Co",
    "领克": "Lynk & Co",
    "deepal": "Deepal",
    "深蓝": "Deepal",
    "aito": "AITO",
    "问界": "AITO",
    "gac trumpchi": "GAC Trumpchi",
    "trumpchi": "GAC Trumpchi",
    "传祺": "GAC Trumpchi",
    "广汽传祺": "GAC Trumpchi",
    "chery": "Chery",
    "奇瑞": "Chery",
    "changan": "Changan",
    "长安": "Changan",
    "长安汽车": "Changan",
    "wey": "WEY",
    "魏牌": "WEY",
    "zeekr": "ZEEKR",
    "极氪": "ZEEKR",
    "tank": "Tank",
    "坦克": "Tank",
    "ora": "ORA",
    "欧拉": "ORA",
    "leapmotor": "Leap Motor",
    "leap motor": "Leap Motor",
    "零跑": "Leap Motor",
    "neta": "NETA",
    "哪吒": "NETA",
    "avatr": "Avatr",
    "阿维塔": "Avatr",
    "gm": "GM",
    "上汽通用": "GM",
    "apple": "Apple",
    "苹果": "Apple",
    "蘋果": "Apple",
    "samsung": "Samsung",
    "三星": "Samsung",
    "huawei": "Huawei",
    "华为": "Huawei",
    "華為": "Huawei",
    "xiaomi": "Xiaomi",
    "小米": "Xiaomi",
    "oppo": "OPPO",
    "vivo": "vivo",
    "oneplus": "OnePlus",
    "一加": "OnePlus",
    "loreal": "L'Oréal",
    "l'oreal": "L'Oréal",
    "欧莱雅": "L'Oréal",
    "歐萊雅": "L'Oréal",
    "lancome": "Lancôme",
    "兰蔻": "Lancôme",
    "蘭蔻": "Lancôme",
    "estee lauder": "Estée Lauder",
    "雅诗兰黛": "Estée Lauder",
    "shiseido": "Shiseido",
    "资生堂": "Shiseido",
    "dyson": "Dyson",
    "戴森": "Dyson",
    "irobot": "iRobot",
    "ecovacs": "Ecovacs",
    "科沃斯": "Ecovacs",
    "roborock": "Roborock",
    "石头": "Roborock",
    "dreame": "Dreame",
    "追觅": "Dreame",
}
